### PR TITLE
feat: build wasm in common wasm-builder

### PR DESCRIPTION
**Pull request by mhdawson**
Refs: https://github.com/nodejs/security-wg/issues/1236

Update to build in docker using wasm-builder image maintained in https://github.com/nodejs/wasm-builder.

As a side effect this also updates the versions of the wasm tools to a newer version.

undici and amaro have already been moved over and I plan to document in Node.js docs that this is the projects standard way to build WASM blobs.

### CODE REVIEW

**Comment by mhdawson** [comment]
This action https://github.com/nodejs/cjs-module-lexer/blob/main/.github/workflows/build.yml might need an update if there is any setup required to use docker (I'm not sure if there is or not, we'll find out as soon as the action runs).  

Either way it likely needs an update to remove the steps that install the wasi sdk etc. as they will no longer be needed after this PR lands.

**Comment by mhdawson** [comment]
@guybedford FYI as discussed. Have already moved over undici and amaro, so the cjs-module-lexer is the last one.

**Comment by mhdawson** [comment]
Looks lioke the test will never run as its trying to use ubuntu18, opened https://github.com/nodejs/cjs-module-lexer/pull/106  to fix that.

In addition I think this will be needed in the action:

      - name: Set up Docker
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

Once https://github.com/nodejs/cjs-module-lexer/pull/106 lands I'll rebase and then update the action to add this as well as remove the parts that are no longer needed.

**Comment by mhdawson** [comment]
@guybedford just needed one small tweak to create the dist directory if it does not exist and build/tests pass.

**Review by guybedford — APPROVED** [review]

**Pull request merged**
